variables:
  SRC_PATH: .
  DOCKERFILE_PATH: .devops
  VALUESFILE_PATH: .devops/2-deploy
  TEST_DISABLED: "true"
  CODE_QUALITY_DISABLED: "true"
  LICENSE_MANAGEMENT_DISABLED: "true"
  PERFORMANCE_DISABLED: "true"
  LOAD_PERFORMANCE_DISABLED: "true"
  SAST_DISABLED: "true"
  SECRET_DETECTION_DISABLED: "true"
  DEPENDENCY_SCANNING_DISABLED: "true"
  CONTAINER_SCANNING_DISABLED: "true"
  DAST_DISABLED: "true"
  POSTGRES_ENABLED: "false"

  WEB_DOMAIN: 24-vnr-hrm
  KUBE_INGRESS_BASE_DOMAIN: dev.3si.vn
  KUBE_INGRESS_BASE_DOMAIN_STG: stg.3si.vn

stages:
  - build
  - deploy

before_script:
  - export VERSION=$CI_COMMIT_SHORT_SHA
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY

include:
  # WEB
  - local: .devops/3-cicd/web.yml
  - local: .devops/3-cicd/web-stg.yml
